spring:
  profiles:
    group:
      "docker": "docker_profile, default_profile"
      "local": "local_profile, default_profile"
---
spring.config.activate.on-profile: default_profile
server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
#Local Exec
spring.config.activate.on-profile: local_profile

spring:
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: ecommerce

---
#Docker
spring.config.activate.on-profile: docker_profile


spring:
  cloud:
    config:
      uri: http://config-service:8888
      name: ecommerce