# 공통으로 적용되는 속성
server.servlet.context-path: /sampleb
spring:
  application:
    name: sampleb
  profiles: default
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER     #Swagger 관련 수정  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
  cloud:
    stream:
      bindings:
        in-sampleAChanged: #입력(Consumer) 채널 (in-토픽이름)
          destination: sampleAChanged   #토픽이름
          contentType: application/json    #데이터형식
          group: CGR-sampleb-sampleAChanged  #consumer 그룹: CGR-MSA이름-토픽이름
  datasource:
    #  url: jdbc:mysql://mysql/samplea?useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://vm-mysql13.mysql.database.azure.com:3306/samplea?useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: pwd
    hikari.initializationFailTimeout: 30000

hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect

---
server.port: 8092

spring:
  profiles: local
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
# MONGODB (MongoProperties)
spring.data.mongodb.uri: mongodb://localhost:27017/SKMSA

#Zipkin
spring.zipkin.base-url: http://localhost:9411/
logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}] [%thread] %-5level %logger{36} - %msg%n"


---
### 여기부터는 Docker 기반 설정
server.port: 8080

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
# MONGODB (MongoProperties)
spring.data.mongodb.uri: mongodb://mongo:27017/SKMSA
