version: '2'
services:
  discovery-service:
    container_name: discovery-service
    image: msa2023/discovery-service:1.0
    ports:
      - "4116:8761"
    environment:
      - spring.profiles.active=docker
#    depends_on:
#      - config-service
    networks: 
      my-network:


networks: 
  my-network:
    external: true
    name: ecommerce-network
