version: '2'
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "4126:9411"
    networks:
      my-network:

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "4131:9090"
    volumes:
      - "/home/msa2023/inflearn-2022-SpringCloudMSA/workspace/docker-prometheus/prometheus-docker.yml:/etc/prometheus/prometheus.yml"
    networks:
      my-network:

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "4133:3000"
    networks:
      my-network:

networks:
  my-network:
    external: true
    name: ecommerce-network