version: '2'
services:
  discovery-service:
    image: jcscom13/discovery-service:1.0
    ports:
      - "4116:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker default
#    depends_on:
#      - config-service
    networks:
      my-network:

networks:
  my-network:
    external: true
    name: ecommerce-network

