version: '2'
services:
  config-service:
    container_name: config-service
    image: msa2023/config-service:1.0
    ports:
      - "4111:8888"
    environment:
      - spring.profiles.active=docker
#    depends_on:
#      - rabbitmq
    networks:
      my-network:

networks:
  my-network:
    external: true
    name: ecommerce-network
