version: '2'
services:
  catalog-service:
    container_name: catalog-service
    image: msa2023/catalog-service:1.0
    environment:
      - spring.profiles.active=docker
#      - logging.file=/api-logs/users-ws.log
#    depends_on:
#      - apigateway-service
    networks:
      my-network:

networks:
  my-network:
    external: true
    name: ecommerce-network
