version: '2'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    mem_limit: 200m
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks: 
      my-network:
        ipv4_address: 172.19.0.100

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    mem_limit: 500m
    depends_on:
      - zookeeper
    ports:
      - 4192:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Docker용
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      #Local 용
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      my-network:
        ipv4_address: 172.19.0.101      

networks: 
  my-network:
    external: true
    name: ecommerce-network        