version: '2'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    mem_limit: 200m
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks: 
      my-network:
        ipv4_address: 172.19.0.100

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    mem_limit: 500m
    depends_on:
      - zookeeper
#    ports:
#      - "4192:4192"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.19.0.101
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: AA:PLAINTEXT, BB:PLAINTEXT
      KAFKA_LISTENERS: AA://kafka:9092, BB://kafka:4192
      KAFKA_ADVERTISED_LISTENERS: AA://kafka:9092, BB://10.250.141.146:4192
      KAFKA_INTER_BROKER_LISTENER_NAME: AA


    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      my-network:
        ipv4_address: 172.19.0.101      

networks: 
  my-network:
    external: true
    name: ecommerce-network        