spring:
  profiles:
    group:
      "docker": "docker_profile, default_profile"
      "local": "local_profile, default_profile"
---
spring.config.activate.on-profile: default_profile
server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  profiles:
#    active: default
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myinno/spring-cloud-config
#          basedir: /Users/dowonlee/Desktop/Work/tmp/config-repo
#          username: [username]
#          password: [password]
#        native:
#          search-locations: file:///d:/APP/@inflearn/inflearn-2022-SpringCloudMSA/native-file-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

---
#Local Exec
spring.config.activate.on-profile: local_profile

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
---
#Docker
spring.config.activate.on-profile: docker_profile

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest