server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
#    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/dowonlee/Desktop/Work/git-local-repo
          uri: https://github.com/myinno/spring-cloud-config
#          basedir: /Users/dowonlee/Desktop/Work/tmp/config-repo
#          username: [username]
#          password: [password]
        native:
          search-locations: file:///d:/APP/@inflearn/inflearn-2022-SpringCloudMSA/native-file-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
